#! /usr/bin/env bash

packages=(
	"tmux"
	"nvm"
	"rbenv"
	"tldr"
	"elixir"
	"ffmpeg"
	"imagemagick"
	"heroku"
	"neovim"
	"rubymine"
	"yarn"
	"cmake"
	"shared-mime-info"
	"vips"
	"redis"
	"elasticsearch"
	"chromedriver"
	"openssl@3"
	"bat"
	"tmuxinator"
	"watch"
	"tree"
  "ripgrep"
  "fd"
  "gh"
)

brew update

for pkg in "${packages[@]}"; do
	if brew list -1 | grep -q "^${pkg}\$"; then
		echo "Package '$pkg' is already installed"
	else
		echo "Installing package '$pkg'"
		brew install $pkg
	fi
done
