#! /opt/homebrew/bin/bash

branch=$(git branch --format="%(refname:short)" --sort=-committerdate | fzf)

if [[ -n "$branch" ]]; then
  git switch "$branch"
else
  echo "No branch selected. Exiting."
fi
