#! /usr/local/bin/bash

read -p "input file type (mkv, mp4, etc...): " input_type
read -p "output file type (default for chromecast is mp4...): " output_type

new_dir="$(pwd)_CONVERTED_TO_${output_type}"

mkdir -p $new_dir

for file in $(ls -p | grep -v / | grep "${input_type}" ); do
  ffmpeg -i $file -codec copy "${new_dir}/${file%.*}.${output_type}"
done
