#! /usr/local/bin/bash

if [[ "$1" ]]; then
  echo "arg is equal to ${1}"
  file_ext="$1"
else
  file_ext="*"
fi

files_that_changed=$(git status "*.${file_ext}" -s | cut -c 4-)
echo $files_that_changed
