#! /bin/bash

read -p "Are you in the directory with the files you want to convert? (y/n): " answer
if [ "$answer" != "y" ]; then
  echo "Please cd into the directory with the files you want to convert."
  exit 1
else
  echo "Great! Let's get started."
fi

read -p "input file type (mkv, mp4, etc...): " input_type
read -p "output file type (default for chromecast is mp4...): " output_type

new_dir="$(pwd)_CONVERTED_TO_${output_type}"
mkdir -p $new_dir

files=$(ls -p | grep -v / | grep "${input_type}$")

for file in $files; do
  ffmpeg -i "$file" -c copy -c:s mov_text "${new_dir}/${file%.*}.${output_type}" 

  if [ $? -ne 0 ]; then
    echo -e "SOMETHING WENT WRONG WITH COPYING."
  fi
done
