#! /usr/local/bin/bash

readonly FILE=/etc/passwd
read -p "Enter name of the username: " username

result_string=$(grep $username $FILE)

if [ -z "$result_string" ]; then
  echo "User not found"
  exit
fi

OLD_IFS=$IFS
IFS=":"

read user pass uid gid name dir shell <<< "$result_string"

echo "user is:       $user"
echo "pass is:       $pass"
echo "uid is:       $uid"
echo "gid is:       $gid"
echo "name is:       $name"
echo "dir is:       $dir"
echo "shell is:       $shell"

IFS=$OLD_IFS
