#! /bin/bash

readonly FILE=/etc/passwd
read -p "Enter name of the username: " username

result_string=$(grep $username $FILE)
# can also use this:
# result_string=`grep $username $FILE`
# the former is prefered because you can nest it:
# result_string=$(grep $username $(ls /etc/*passwd*))


if [ -z "$result_string" ]; then
  echo "User not found"
  exit
fi

OLD_IFS=$IFS
IFS=":"

read user pass uid gid name dir shell <<< "$result_string"

echo "user is:       $user"
echo "pass is:       $pass"
echo "uid is:       $uid"
echo "gid is:       $gid"
echo "name is:       $name"
echo "dir is:       $dir"
echo "shell is:       $shell"

IFS=$OLD_IFS
