#! /bin/bash

BASH_SCRIPTS="${HOME}/projects/bashdir"

read -p "Filename: " file_name

bash_path=$(which bash)

new_file="${file_name}"

mkdir -p $BASH_SCRIPTS

cd $BASH_SCRIPTS

if [ -f ${new_file} ];then
  echo "File already exists!"
  exit
fi

touch $new_file

chmod +x $new_file
echo $new_file

echo -e "#! ${bash_path}\n" >> $new_file

# cat << EOF >> $new_file
# #! ${bash_path}
# EOF

echo "Done!"
