#! /bin/bash

dir="$1"

if [ ! -d $dir ]; then
  echo "NOT A DIRECTORY"
  exit
fi

if [[ $OSTYPE == "darwin"* ]]; then
  echo "Using ********* UNIX *********"
  counted_files=$(stat -f %Sm $dir/* | cut -c 08-09)
fi

if [[ $OSTYPE == "linux-gnu" ]]; then
  echo "Using ********* LINUX *********"
  counted_files=$(stat -c %y $dir/* | cut -c 12-13)
fi


for k in {0..23};
do
  hours[k]=0;
  # hours[$k]=0;
done


for i in $counted_files;
do
  #strip 0s from the front of the number
  j=${i#0}
  # hours[j]=$(( ${hours[j]} + 1 ))
  hours[$j]=$(( ${hours[$j]} + 1 ))
  # (( hours[j] = ${hours[j]} + 1 ))
done

echo -e "Hours \t Files \t\t Hours \t Files"
echo -e "_____ \t _____ \t\t _____ \t _____"

for k in {0..11};
do
  m=$(( $k + 12 ))
  echo -e "$k \t ${hours[k]} \t\t $m \t ${hours[m]}"
done
