#! /opt/homebrew/bin/bash

project_name=$(basename "$PWD")
patch_path=~/."${project_name}_local_changes.patch"

if [[ -f "$patch_path" ]]; then
  echo "Applying patch from: $patch_path"
  git apply "$patch_path"

  if [[ $? -eq 0 ]]; then
    echo "Patch applied successfully."
  else
    echo "Patch failed to apply. Check for conflicts or apply manually."
  fi
else
  echo "Patch file not found: $patch_path"
fi
