#! /bin/bash

OLD_IFS="$IFS"
IFS=":"

if [ "$1" == "-d" ]; then
  directory="$2"
  for dir in $PATH;
  do
    if [ "$directory" == "$dir" -o "$directory" == "$dir/" ]; then
      echo "FOUND in path: $directory"
    else
      match=$(echo $dir | grep -i $directory)
      if [ "$match" != "" ]; then
        echo "FOUND $directory in $dir"
      fi
    fi
  done
  exit
fi

# Check if a command is present with '-c command'
if [ "$1" == "-c" ]; then
  command="$2"

  for dir in $PATH;
  do
    if [ -e "${dir}/${command}" ]; then
      echo "***COMMAND PRESENT IN PATH***"
      echo $dir/$command
    fi
  done
  exit
fi

# print path delimited by newline
for dir in $PATH;
do
  echo "WELL, I RECON WE'VE GOT OURSELVES A $dir"
done

IFS="$OLD_IFS"
