#! /bin/bash

divider="#***************************"

function append_to_bottom() {
  local file_to_change=$1
  local data_to_push=$2

  echo -e "\n" >> "$file_to_change"
  echo $divider >> "$file_to_change"
  echo "${data_to_push}" >> "$file_to_change"
  echo $divider >> "$file_to_change"
}

function append_to_top() {
  local file_to_change=$1
  local new_file_text=$(cat $file_to_change)
  local data_to_unshift=$2

  echo "${divider}
  ${data_to_unshift}
  ${divider}
  ${new_file_text}" > "$file_to_change"
}

echo "Please name the directory for storing matching files: "
read dirname

read -p "append hits to top or bottom of file? " position

word=$1
folder=$2

cd $folder

mkdir "$dirname"

for file in *
do
  if [ -f "$file" ]; then
    output=$(grep -i -n $word $file)

    if [[ $output ]]; then
      echo "FOUND!";
      cp "$file" "$dirname"

      newfile="${dirname}/${file}"

      "append_to_${position}" "$newfile" "$output"
    fi
  else
    echo "$file is not a file"
  fi
  echo "_____________________"
done
